/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PskChapter {
        "guid": string;
        "title": string;
    }
    interface PskChapterWrapper {
        "title": string;
    }
    interface PskCode {
        "language": string;
        "title": string;
    }
    interface PskDescription {
        "title": string;
    }
    interface PskExample {
        "title": string;
    }
    interface PskLiveCode {
        "language": string;
        "value": string;
    }
    interface PskTable {
        "cellsWidth": string;
        "footer": boolean;
        "header": boolean;
    }
    interface PskToc {
        "title": string;
    }
}
declare global {
    interface HTMLPskChapterElement extends Components.PskChapter, HTMLStencilElement {
    }
    var HTMLPskChapterElement: {
        prototype: HTMLPskChapterElement;
        new (): HTMLPskChapterElement;
    };
    interface HTMLPskChapterWrapperElement extends Components.PskChapterWrapper, HTMLStencilElement {
    }
    var HTMLPskChapterWrapperElement: {
        prototype: HTMLPskChapterWrapperElement;
        new (): HTMLPskChapterWrapperElement;
    };
    interface HTMLPskCodeElement extends Components.PskCode, HTMLStencilElement {
    }
    var HTMLPskCodeElement: {
        prototype: HTMLPskCodeElement;
        new (): HTMLPskCodeElement;
    };
    interface HTMLPskDescriptionElement extends Components.PskDescription, HTMLStencilElement {
    }
    var HTMLPskDescriptionElement: {
        prototype: HTMLPskDescriptionElement;
        new (): HTMLPskDescriptionElement;
    };
    interface HTMLPskExampleElement extends Components.PskExample, HTMLStencilElement {
    }
    var HTMLPskExampleElement: {
        prototype: HTMLPskExampleElement;
        new (): HTMLPskExampleElement;
    };
    interface HTMLPskLiveCodeElement extends Components.PskLiveCode, HTMLStencilElement {
    }
    var HTMLPskLiveCodeElement: {
        prototype: HTMLPskLiveCodeElement;
        new (): HTMLPskLiveCodeElement;
    };
    interface HTMLPskTableElement extends Components.PskTable, HTMLStencilElement {
    }
    var HTMLPskTableElement: {
        prototype: HTMLPskTableElement;
        new (): HTMLPskTableElement;
    };
    interface HTMLPskTocElement extends Components.PskToc, HTMLStencilElement {
    }
    var HTMLPskTocElement: {
        prototype: HTMLPskTocElement;
        new (): HTMLPskTocElement;
    };
    interface HTMLElementTagNameMap {
        "psk-chapter": HTMLPskChapterElement;
        "psk-chapter-wrapper": HTMLPskChapterWrapperElement;
        "psk-code": HTMLPskCodeElement;
        "psk-description": HTMLPskDescriptionElement;
        "psk-example": HTMLPskExampleElement;
        "psk-live-code": HTMLPskLiveCodeElement;
        "psk-table": HTMLPskTableElement;
        "psk-toc": HTMLPskTocElement;
    }
}
declare namespace LocalJSX {
    interface PskChapter {
        "guid"?: string;
        "onPsk-send-chapter"?: (event: CustomEvent<any>) => void;
        "title"?: string;
    }
    interface PskChapterWrapper {
        "title"?: string;
    }
    interface PskCode {
        "language"?: string;
        "title"?: string;
    }
    interface PskDescription {
        "title"?: string;
    }
    interface PskExample {
        "title"?: string;
    }
    interface PskLiveCode {
        "language"?: string;
        "value"?: string;
    }
    interface PskTable {
        "cellsWidth"?: string;
        "footer"?: boolean;
        "header"?: boolean;
    }
    interface PskToc {
        "title"?: string;
    }
    interface IntrinsicElements {
        "psk-chapter": PskChapter;
        "psk-chapter-wrapper": PskChapterWrapper;
        "psk-code": PskCode;
        "psk-description": PskDescription;
        "psk-example": PskExample;
        "psk-live-code": PskLiveCode;
        "psk-table": PskTable;
        "psk-toc": PskToc;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "psk-chapter": LocalJSX.PskChapter & JSXBase.HTMLAttributes<HTMLPskChapterElement>;
            "psk-chapter-wrapper": LocalJSX.PskChapterWrapper & JSXBase.HTMLAttributes<HTMLPskChapterWrapperElement>;
            "psk-code": LocalJSX.PskCode & JSXBase.HTMLAttributes<HTMLPskCodeElement>;
            "psk-description": LocalJSX.PskDescription & JSXBase.HTMLAttributes<HTMLPskDescriptionElement>;
            "psk-example": LocalJSX.PskExample & JSXBase.HTMLAttributes<HTMLPskExampleElement>;
            "psk-live-code": LocalJSX.PskLiveCode & JSXBase.HTMLAttributes<HTMLPskLiveCodeElement>;
            "psk-table": LocalJSX.PskTable & JSXBase.HTMLAttributes<HTMLPskTableElement>;
            "psk-toc": LocalJSX.PskToc & JSXBase.HTMLAttributes<HTMLPskTocElement>;
        }
    }
}
